### ISSUE TITLE
OptDefinition cmd_path: throws an error when used

### ISSUE THREAD

**Issue by rsb** [engine8/fuelcell#23]
./bin/test --all=foo blah
/Users/Robert.Scott-Buccleuch/projects/rsb/fuelcell/lib/fuelcell/cli.rb:75:in `handle_callable_option': undefined method `cmd_ath' for #<Fuelcell::Action::OptDefinition:0x007fedfa952190> (NoMethodError)
        from /Users/Robert.Scott-Buccleuch/projects/rsb/fuelcell/lib/fuelcell/cli.rb:66:in `execute'
        from /Users/Robert.Scott-Buccleuch/projects/rsb/fuelcell/lib/fuelcell.rb:110:in `start'
        from ./bin/test:7:in `<main>'

**Comment by rsb** [comment]
added into 0.2.2
